{{- define "hostname-suffix" }}
{{- if eq .Values.subdomain true }}
{{- printf ".%s.codemowers.cloud" .Values.username }}
{{- else }}
{{- printf "-%s.codemowers.ee" .Values.username }}
{{- end }}
{{- end }}

{{- define "domain" }}
{{- if eq .Values.subdomain true }}
{{- printf "%s.codemowers.cloud" .Values.username }}
{{- else }}
{{- printf ".codemowers.ee" .Values.username }}
{{- end }}
{{- end }}

{{ define "tls" }}
{{ if eq .Values.subdomain true }}
  tls:
  - hosts:
    - "*.{{ .Values.username }}.codemowers.cloud"
    secretName: wildcard-tls
{{ else }}
  tls:
  - hosts:
    - "*.codemowers.ee"
{{ end }}
{{ end }}


{{ define "ingress-annotations" }}
{{ if eq .Values.traefik.dedicated true }}
    external-dns.alpha.kubernetes.io/target: "traefik{{- template "hostname-suffix" . }}"
    kubernetes.io/ingress.class: "{{ .Release.Namespace }}"
{{ else }}
    external-dns.alpha.kubernetes.io/target: "traefik.codemowers.ee"
    kubernetes.io/ingress.class: shared
{{ end }}
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: playground-user-{{ .Values.username }}
  namespace: "{{ .Release.Namespace }}"
subjects:
- kind: User
  name: "{{ .Values.email }}"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
