---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: playground-user-{{ .Values.username }}
subjects:
- kind: User
  name: "https://auth.codemowers.eu/#{{ .Values.username }}"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: playground-users
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: playground-user-{{ .Values.username }}-view
subjects:
- kind: User
  name: "https://auth.codemowers.eu/#{{ .Values.username }}"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: playground-user-{{ .Values.username }}-view-extra
subjects:
- kind: User
  name: "https://auth.codemowers.eu/#{{ .Values.username }}"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view-extra
  apiGroup: rbac.authorization.k8s.io
