---
apiVersion: codemowers.cloud/v1beta1
kind: ClusterHarborProject
metadata:
  name: {{ .Values.username }}
spec: {}
---
apiVersion: codemowers.cloud/v1beta1
kind: HarborCredential
metadata:
  name: kaniko
spec:
  project: {{ .Values.username }}
  key: config.json
  permissions:
    - resource: repository
      action: pull
    - resource: tag
      action: create
    - resource: repository
      action: push
---
apiVersion: codemowers.cloud/v1beta1
kind: HarborCredential
metadata:
  name: regcred
spec:
  project: {{ .Values.username }}
  type: kubernetes.io/dockerconfigjson
  key: .dockerconfigjson
  permissions:
    - resource: repository
      action: pull
